name: Download the latest data from DISCOSweb
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  extract:
  name: Test Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get DiscosExtractor Release
        run: wget https://github.com/hughesjs/DiscosExtractor/releases/download/v0.1/discosextractor && echo "{\"DiscosApiUrl\":\"https://discosweb.esoc.esa.int/api/\",\"DiscosApiKey\":\"${{secrets.DISCOS_TOKEN}}\"}" >> .discosextractorrc
      - name: Fetch Latest Data from DISCOSweb
        run: ./discosextractor fetch
      - name: Copy file to raw directory
        run: mv ./resultsdict.json ./data/raw/discos-$(date +%Y%m%d).json
      - name: Test
        run: ls -la ./data/raw/
